export interface WarmupTopic {
  id: string;
  label: string;
  difficulty: 'easy' | 'medium';
  theme: string;
  phrases: string[];
}

export const WARMUP_TOPICS: WarmupTopic[] = [
  // Easy — Vie quotidienne
  {
    id: 'se-presenter',
    label: 'Se présenter',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "Je m'appelle… et je viens de…",
      "J'habite à… depuis… ans.",
      "Dans ma vie quotidienne, je travaille comme…",
      "Ce qui me définit le mieux, c'est…",
      "En dehors du travail, j'aime surtout…",
      "Mon plus grand défi en ce moment, c'est…",
    ],
  },
  {
    id: 'routine-quotidienne',
    label: 'Ma routine quotidienne',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "Je commence généralement ma journée par…",
      "Le matin, j'ai l'habitude de…",
      "Ce qui structure ma semaine, c'est…",
      "Le soir, je consacre du temps à…",
      "Ce que j'essaie de ne jamais sauter, c'est…",
      "Ma routine a changé depuis que…",
    ],
  },
  {
    id: 'famille',
    label: 'La famille',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "Dans ma famille, nous sommes… personnes.",
      "Je m'entends très bien avec… parce que…",
      "Ce qui unit notre famille, c'est surtout…",
      "Quand on se retrouve tous ensemble, on aime…",
      "La personne qui m'a le plus influencé, c'est…",
      "Pour moi, la famille signifie avant tout…",
    ],
  },
  {
    id: 'logement',
    label: 'Mon logement',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "J'habite dans un appartement / une maison situé(e)…",
      "Ce que j'apprécie le plus chez moi, c'est…",
      "Mon loyer s'élève à… par mois.",
      "Ce qui manque à mon logement actuel, c'est…",
      "Le quartier où je vis est plutôt…",
      "Idéalement, j'aimerais un logement qui…",
    ],
  },
  {
    id: 'repas-cuisine',
    label: 'Les repas et la cuisine',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "En semaine, je mange plutôt…",
      "Le plat que je prépare le plus souvent, c'est…",
      "Ce que j'aime dans la cuisine, c'est…",
      "Je fais mes courses généralement…",
      "Un repas en famille, ça ressemble à…",
      "La cuisine que je préfère au restaurant, c'est…",
    ],
  },
  {
    id: 'loisirs',
    label: 'Mes loisirs et passions',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "Pendant mon temps libre, je préfère…",
      "Ma passion depuis longtemps, c'est…",
      "Je consacre environ… heures par semaine à…",
      "Ce qui me détend vraiment, c'est…",
      "J'ai commencé à… il y a… ans et depuis…",
      "Ce que j'aimerais explorer comme nouveau loisir, c'est…",
    ],
  },
  {
    id: 'animaux',
    label: 'Les animaux de compagnie',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "J'ai un(e)… qui s'appelle… depuis…",
      "Ce que j'aime le plus chez mon animal, c'est…",
      "Prendre soin d'un animal, ça demande…",
      "Avoir un animal de compagnie m'apporte…",
      "Pour moi, les animaux jouent un rôle important parce que…",
      "Si je pouvais adopter un autre animal, ce serait…",
    ],
  },
  {
    id: 'amis',
    label: 'Les amis et la vie sociale',
    difficulty: 'easy',
    theme: 'Vie quotidienne',
    phrases: [
      "Je me retrouve souvent avec mes amis pour…",
      "Mon ami(e) le/la plus proche, c'est… parce que…",
      "Quand je veux sortir, je propose généralement…",
      "Ce qui est important pour moi dans une amitié, c'est…",
      "Depuis mon arrivée au Canada, j'ai rencontré…",
      "Je garde le contact avec mes amis d'enfance en…",
    ],
  },

  // Easy — Achats & Transports
  {
    id: 'achats-commerces',
    label: 'Les achats et les commerces',
    difficulty: 'easy',
    theme: 'Achats & Transports',
    phrases: [
      "Je fais mes courses principalement à…",
      "Ce que j'achète en ligne plutôt qu'en magasin, c'est…",
      "Quand je cherche un bon prix, je…",
      "Mon budget mensuel pour les achats courants est environ…",
      "Ce que je n'achète jamais sans comparer les prix, c'est…",
      "Le marché / l'épicerie que je préfère, c'est… parce que…",
    ],
  },
  {
    id: 'transports',
    label: 'Les transports en commun',
    difficulty: 'easy',
    theme: 'Achats & Transports',
    phrases: [
      "Pour aller au travail, je prends généralement…",
      "Le trajet que je fais le plus souvent dure environ…",
      "Ce que j'apprécie dans les transports en commun, c'est…",
      "En hiver, se déplacer au Canada, c'est…",
      "Je préfère le métro / l'autobus parce que…",
      "Depuis que j'utilise…, mes déplacements sont…",
    ],
  },
  {
    id: 'meteo-saisons',
    label: 'La météo et les saisons',
    difficulty: 'easy',
    theme: 'Achats & Transports',
    phrases: [
      "La saison que je préfère au Canada, c'est… parce que…",
      "En hiver, les températures peuvent descendre jusqu'à…",
      "Ce qui m'a surpris dans le climat canadien, c'est…",
      "Quand il fait froid, j'aime surtout…",
      "Pour m'adapter aux hivers canadiens, j'ai appris à…",
      "L'été à Montréal / Ottawa / Toronto, c'est…",
    ],
  },

  // Medium — Travail & Études
  {
    id: 'travail-ambitions',
    label: 'Le travail et les ambitions',
    difficulty: 'medium',
    theme: 'Travail & Études',
    phrases: [
      "Dans mon domaine, ce qui me motive le plus c'est…",
      "À moyen terme, j'aimerais évoluer vers un poste de…",
      "Ce que je cherche dans un environnement de travail, c'est…",
      "L'expérience professionnelle qui m'a le plus formé(e), c'est…",
      "Pour atteindre mes objectifs, je compte…",
      "Ce qui distingue le marché du travail canadien, à mon avis, c'est…",
    ],
  },
  {
    id: 'etudes-formation',
    label: 'Les études et la formation',
    difficulty: 'medium',
    theme: 'Travail & Études',
    phrases: [
      "J'ai étudié… pendant… ans à…",
      "La formation qui m'a le plus apporté professionnellement, c'est…",
      "Au Québec / au Canada, le système scolaire fonctionne…",
      "Ce que j'aurais fait différemment dans mon parcours, c'est…",
      "Pour se reconvertir au Canada, il est souvent nécessaire de…",
      "La formation continue est importante pour moi parce que…",
    ],
  },
  {
    id: 'recherche-emploi',
    label: "La recherche d'emploi",
    difficulty: 'medium',
    theme: 'Travail & Études',
    phrases: [
      "Lors de ma recherche d'emploi, j'ai constaté que…",
      "Le plus grand défi pour trouver un emploi au Canada, c'est…",
      "Pour préparer un entretien, je…",
      "Mon CV a été adapté au marché canadien en…",
      "Les compétences les plus recherchées dans mon domaine sont…",
      "Grâce à mon réseau professionnel, j'ai pu…",
    ],
  },
  {
    id: 'vie-bureau',
    label: 'La vie au bureau',
    difficulty: 'medium',
    theme: 'Travail & Études',
    phrases: [
      "Dans mon équipe, l'ambiance est plutôt…",
      "Ce qui me plaît dans la culture de travail au Canada, c'est…",
      "En réunion, j'essaie toujours de…",
      "Le télétravail a changé ma façon de travailler en…",
      "Quand il y a un conflit au bureau, je préfère…",
      "L'équilibre travail-vie personnelle ici, c'est…",
    ],
  },

  // Medium — Canada & Immigration
  {
    id: 'immigration-integration',
    label: "L'immigration et l'intégration",
    difficulty: 'medium',
    theme: 'Canada & Immigration',
    phrases: [
      "Ce qui m'a poussé(e) à immigrer au Canada, c'est…",
      "Les premières semaines après mon arrivée ont été…",
      "S'intégrer dans une nouvelle société, ça passe par…",
      "La langue française a été pour moi un atout parce que…",
      "Ce que j'aurais aimé savoir avant d'immigrer, c'est…",
      "L'aspect culturel qui m'a demandé le plus d'adaptation, c'est…",
    ],
  },
  {
    id: 'logement-canada',
    label: 'Se loger au Canada',
    difficulty: 'medium',
    theme: 'Canada & Immigration',
    phrases: [
      "Trouver un logement à… n'est pas facile parce que…",
      "Le coût de la vie dans les grandes villes canadiennes…",
      "Pour louer un appartement, il faut généralement fournir…",
      "La différence entre un bail au Québec et ailleurs, c'est…",
      "Les droits des locataires au Canada incluent…",
      "Pour trouver mon logement actuel, j'ai utilisé…",
    ],
  },
  {
    id: 'systeme-sante-canada',
    label: 'Le système de santé canadien',
    difficulty: 'medium',
    theme: 'Canada & Immigration',
    phrases: [
      "Au Canada, les soins de santé sont couverts par…",
      "Pour avoir accès à la carte d'assurance maladie, il faut…",
      "Ce qui distingue le système de santé canadien, c'est…",
      "L'accès à un médecin de famille peut prendre…",
      "En cas d'urgence, on peut se rendre à…",
      "Les médicaments et les soins dentaires sont…",
    ],
  },
  {
    id: 'culture-canadienne',
    label: 'La culture et les traditions canadiennes',
    difficulty: 'medium',
    theme: 'Canada & Immigration',
    phrases: [
      "Ce qui m'a le plus frappé(e) dans la culture canadienne, c'est…",
      "Au Québec, la culture francophone se manifeste par…",
      "Les fêtes et traditions canadiennes que j'apprécie le plus…",
      "La diversité culturelle au Canada se ressent dans…",
      "Ce que les Canadiens valorisent beaucoup, c'est…",
      "Comparer la culture canadienne à la mienne, je dirais que…",
    ],
  },

  // Medium — Société & Environnement
  {
    id: 'environnement-ecologie',
    label: "L'environnement et l'écologie",
    difficulty: 'medium',
    theme: 'Société & Environnement',
    phrases: [
      "Pour réduire mon empreinte écologique, j'essaie de…",
      "Le changement climatique se ressent déjà dans…",
      "Les politiques environnementales au Canada…",
      "Ce que les individus peuvent faire concrètement, c'est…",
      "La question du recyclage au Québec est particulière parce que…",
      "Si on ne change pas nos habitudes, dans 20 ans…",
    ],
  },
  {
    id: 'vie-ville-campagne',
    label: 'Vie en ville vs à la campagne',
    difficulty: 'medium',
    theme: 'Société & Environnement',
    phrases: [
      "Vivre en ville offre l'avantage de…",
      "La campagne attire ceux qui recherchent…",
      "Depuis la pandémie, beaucoup de gens ont décidé de…",
      "Le coût de la vie en région est souvent…",
      "Ce que je ne pourrais pas sacrifier en quittant la ville, c'est…",
      "Pour les familles avec enfants, la campagne présente…",
    ],
  },
  {
    id: 'benevolat',
    label: "Le bénévolat et l'engagement",
    difficulty: 'medium',
    theme: 'Société & Environnement',
    phrases: [
      "Je fais du bénévolat auprès de… parce que…",
      "S'engager dans sa communauté permet de…",
      "Le bénévolat m'a appris à…",
      "Les organismes communautaires au Canada jouent un rôle…",
      "Ce qui motive les bénévoles, c'est souvent…",
      "Pour quelqu'un qui arrive au Canada, le bénévolat est utile car…",
    ],
  },
  {
    id: 'medias-reseaux-sociaux',
    label: 'Les médias et les réseaux sociaux',
    difficulty: 'medium',
    theme: 'Société & Environnement',
    phrases: [
      "Je m'informe principalement via…",
      "Les réseaux sociaux ont changé la façon dont…",
      "Ce qui me préoccupe dans la désinformation, c'est…",
      "Je passe environ… heures par jour sur les réseaux sociaux.",
      "La liberté de la presse est importante parce que…",
      "Pour distinguer une vraie information d'une fausse, je…",
    ],
  },
  {
    id: 'education-enfants',
    label: 'L\'éducation des enfants',
    difficulty: 'medium',
    theme: 'Société & Environnement',
    phrases: [
      "Le système scolaire québécois / canadien fonctionne…",
      "Ce que j'apprécie dans l'éducation ici, c'est…",
      "Les parents jouent un rôle essentiel en…",
      "Les activités parascolaires permettent aux enfants de…",
      "Comparer l'éducation ici et dans mon pays d'origine, je dirais…",
      "Pour préparer un enfant à réussir, il est important de…",
    ],
  },

  // Medium — Santé & Bien-être
  {
    id: 'sante-habitudes',
    label: 'La santé et les habitudes de vie',
    difficulty: 'medium',
    theme: 'Santé & Bien-être',
    phrases: [
      "Pour rester en bonne santé, je fais attention à…",
      "Une alimentation équilibrée, pour moi, ça veut dire…",
      "Depuis que j'ai changé mon mode de vie, je…",
      "Le sommeil est crucial parce que…",
      "Ce que les Canadiens font bien en matière de santé publique, c'est…",
      "La prévention est plus importante que le traitement parce que…",
    ],
  },
  {
    id: 'sport-activites',
    label: 'Le sport et les activités physiques',
    difficulty: 'medium',
    theme: 'Santé & Bien-être',
    phrases: [
      "Je pratique… régulièrement depuis…",
      "Le sport que j'aimerais apprendre au Canada, c'est…",
      "Faire de l'exercice m'aide à…",
      "L'hiver ne m'empêche pas de faire du sport parce que…",
      "Les activités sportives en famille, ça nous permet de…",
      "Pour rester motivé(e), j'ai besoin de…",
    ],
  },
  {
    id: 'bien-etre-stress',
    label: 'Le bien-être et la gestion du stress',
    difficulty: 'medium',
    theme: 'Santé & Bien-être',
    phrases: [
      "Quand je me sens stressé(e), j'ai tendance à…",
      "Ce qui m'aide le plus à décompresser, c'est…",
      "La santé mentale est un sujet qui…",
      "Depuis mon immigration, les sources de stress ont changé : maintenant…",
      "Pour trouver un équilibre entre vie pro et perso, je…",
      "Prendre soin de soi, pour moi, ça se traduit par…",
    ],
  },

  // Medium — Voyages & Culture
  {
    id: 'voyages-destinations',
    label: 'Les voyages et les destinations',
    difficulty: 'medium',
    theme: 'Voyages & Culture',
    phrases: [
      "Le voyage qui m'a le plus marqué(e), c'est…",
      "Ce que je recherche quand je voyage, c'est…",
      "Au Canada, j'aimerais encore visiter…",
      "Voyager permet de…",
      "La différence entre voyager en touriste et s'installer, c'est…",
      "Avant de partir en voyage, je prépare toujours…",
    ],
  },
  {
    id: 'technologie-quotidien',
    label: 'La technologie au quotidien',
    difficulty: 'medium',
    theme: 'Voyages & Culture',
    phrases: [
      "La technologie a simplifié ma vie en…",
      "L'outil numérique que j'utilise le plus, c'est…",
      "Ce qui m'inquiète dans notre dépendance à la technologie, c'est…",
      "L'intelligence artificielle va probablement changer…",
      "La protection des données personnelles est importante parce que…",
      "Pour les démarches administratives au Canada, la technologie permet de…",
    ],
  },
  {
    id: 'argent-budget',
    label: "L'argent et le budget",
    difficulty: 'medium',
    theme: 'Voyages & Culture',
    phrases: [
      "Pour gérer mon budget, j'utilise…",
      "Les dépenses qui ont le plus changé depuis mon arrivée, c'est…",
      "Le coût de la vie au Canada m'a surpris parce que…",
      "Pour économiser, j'ai pris l'habitude de…",
      "La différence entre le système bancaire canadien et celui de mon pays…",
      "Avoir un fonds d'urgence est essentiel parce que…",
    ],
  },
];
